# Setup
title:               nan-Af
tagline:             'A curious soul'
description:         'I am Ahmad Afnan Amjad, and this is my personal blog, a home for my projects, experiments, and occasional random insights.'
# 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://nan-af.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ahmad Afnan Amjad
  url:               https://nan-af.github.io
  email:             afnanmughal@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-170829036-1
